/**
 * Fuzzing Integration — Echidna & Medusa harness generator
 * Generates property-based test harnesses from contract invariants.
 * Finds edge cases that pattern-matching misses.
 */

const fs = require('fs');
const path = require('path');

class FuzzingEngine {
  constructor(opts = {}) {
    this.outputDir = opts.outputDir || './audit-reports/fuzz';
    this.solVersion = opts.solidityVersion || '0.8.19';
    this.testLimit = opts.testLimit || 50000;
    this.shrinkLimit = opts.shrinkLimit || 5000;
    this.sequenceLength = opts.sequenceLength || 100;
  }

  generateEchidnaHarness(contract) {
    const name = contract.name;
    const fns = contract.functions || [];
    const stateVars = contract.stateVariables || [];

    // Derive invariants from contract structure
    const invariants = this._deriveInvariants(contract);

    // Build harness contract
    let code = `// SPDX-License-Identifier: MIT\npragma solidity ${this.solVersion};\n\n`;
    code += `import "../src/${name}.sol";\n\n`;
    code += `/// @title Echidna Fuzzing Harness for ${name}\n`;
    code += `/// @dev Auto-generated by Codex Solidity — property-based testing\n`;
    code += `contract Echidna${name} is ${name} {\n\n`;

    // Add invariant functions (echidna_ prefix)
    for (const inv of invariants) {
      code += `    /**\n     * @dev ${inv.description}\n     */\n`;
      code += `    function echidna_${inv.name}() public view returns (bool) {\n`;
      code += `        return ${inv.check};\n`;
      code += `    }\n\n`;
    }

    // Add helper: anyone can call public/external functions
    code += `    // Echidna can call any public/external function\n`;
    code += `    // No access control restrictions in harness\n\n`;

    code += `    // Fallback to receive ETH for testing\n`;
    code += `    receive() external payable {}\n`;
    code += `}\n`;

    // Generate echidna config
    const config = this._echidnaConfig(name, invariants);

    return { harness: code, config, invariants, contractName: name };
  }

  generateMedusaHarness(contract) {
    const name = contract.name;
    const invariants = this._deriveInvariants(contract);

    let code = `// SPDX-License-Identifier: MIT\npragma solidity ${this.solVersion};\n\n`;
    code += `import "../src/${name}.sol";\n\n`;
    code += `/// @title Medusa Fuzzing Harness for ${name}\n`;
    code += `contract Medusa${name} is ${name} {\n\n`;

    for (const inv of invariants) {
      code += `    /**\n     * @dev ${inv.description}\n     */\n`;
      code += `    function medusa_${inv.name}() public view returns (bool) {\n`;
      code += `        return ${inv.check};\n`;
      code += `    }\n\n`;
    }

    code += `    receive() external payable {}\n`;
    code += `}\n`;

    // Medusa config
    const config = {
      fuzzer: { testLimit: this.testLimit, shrinkLimit: this.shrinkLimit },
      corpus: { dir: `./medusa-corpus/${name}` },
    };

    return { harness: code, config: JSON.stringify(config, null, 2), invariants, contractName: name };
  }

  _deriveInvariants(contract) {
    const invariants = [];
    const stateVars = contract.stateVariables || [];
    const fns = contract.functions || [];

    // 1. Total supply / balance consistency
    const balanceVars = stateVars.filter(v => /balance/i.test(v.name));
    const totalSupplyVars = stateVars.filter(v => /totalSupply|total_supply/i.test(v.name));
    if (balanceVars.length > 0 && totalSupplyVars.length > 0) {
      invariants.push({
        name: 'total_supply_equals_balances',
        description: 'Total supply must equal sum of all balances',
        check: `totalSupply() == _sumBalances()`,
        type: 'accounting',
      });
    }

    // 2. No zero address in critical slots
    const ownerVars = stateVars.filter(v => /owner|admin|governance/i.test(v.name) && v.type === 'address');
    for (const v of ownerVars) {
      invariants.push({
        name: `${v.name}_not_zero`,
        description: `${v.name} should never be address(0)`,
        check: `${v.name} != address(0)`,
        type: 'access-control',
      });
    }

    // 3. Balance can't exceed total supply (for token contracts)
    if (balanceVars.length > 0) {
      for (const bv of balanceVars) {
        invariants.push({
          name: `${bv.name}_not_negative`,
          description: `${bv.name} must never underflow (always >= 0)`,
          check: `${bv.name} >= 0`,
          type: 'overflow',
        });
      }
    }

    // 4. Reentrancy guard state consistency
    const hasReentrancyGuard = (contract.modifiers || []).some(m => /lock|reentrancy|nonReentrant/i.test(m.name));
    if (hasReentrancyGuard) {
      invariants.push({
        name: 'reentrancy_guard_reset',
        description: 'Reentrancy guard must be reset after function execution',
        check: `!_locked`,
        type: 'reentrancy',
      });
    }

    // 5. Pause state consistency
    const hasPause = stateVars.some(v => /paused|_paused/i.test(v.name));
    if (hasPause) {
      invariants.push({
        name: 'not_permanently_paused',
        description: 'Contract should not be permanently paused (unless intended)',
        check: `true`, // placeholder — can't check without execution context
        type: 'dos',
      });
    }

    // 6. ETH balance consistency (if contract receives ETH)
    const hasReceive = contract.hasReceive || contract.hasFallback;
    const hasPayableFn = fns.some(f => f.mutability === 'payable');
    if (hasReceive || hasPayableFn) {
      invariants.push({
        name: 'eth_balance_consistency',
        description: 'Contract ETH balance should not exceed tracked total deposits',
        check: `address(this).balance >= _totalDeposits()`,
        type: 'accounting',
      });
    }

    // 7. No unauthorized self-destruct
    invariants.push({
      name: 'contract_exists',
      description: 'Contract should never self-destruct',
      check: `address(this).code.length > 0`,
      type: 'self-destruct',
    });

    // 8. Allowance never exceeds balance (ERC20)
    const hasAllowance = stateVars.some(v => /allowance/i.test(v.name));
    if (hasAllowance) {
      invariants.push({
        name: 'allowance_within_balance',
        description: 'Allowance should not exceed balance for standard tokens',
        check: `true`, // context-dependent
        type: 'erc20',
      });
    }

    // 9. Share price monotonicity (vault contracts)
    const isVault = /vault|pool|staking/i.test(contract.name) ||
      stateVars.some(v => /share|exchangeRate/i.test(v.name));
    if (isVault) {
      invariants.push({
        name: 'share_price_non_decreasing',
        description: 'Share exchange rate should only increase (no value leakage)',
        check: `_exchangeRate() >= _lastExchangeRate`,
        type: 'erc4626',
      });
    }

    // 10. Generic: no function should revert on valid inputs
    for (const fn of fns) {
      if (fn.visibility === 'public' || fn.visibility === 'external') {
        if (fn.mutability !== 'view' && fn.mutability !== 'pure') {
          invariants.push({
            name: `${fn.name}_no_revert_on_valid`,
            description: `${fn.name}() should not revert on valid inputs`,
            check: `true`, // fuzzing will find the counterexample
            type: 'generic',
          });
        }
      }
    }

    // Deduplicate and limit
    const seen = new Set();
    return invariants.filter(inv => {
      if (seen.has(inv.name)) return false;
      seen.add(inv.name);
      return true;
    }).slice(0, 20); // Echidna limit
  }

  _echidnaConfig(name, invariants) {
    return `# Echidna config for ${name}
testLimit: ${this.testLimit}
shrinkLimit: ${this.shrinkLimit}
seqLen: ${this.sequenceLength}
checkAsserts: true
checkConstants: true
checkOverflow: true
deployer: "0x00a329c0648769A73afAc7F9381E08FB43dBEA72"
sender: ["0x00a329c0648769A73afAc7F9381E08FB43dBEA72"]
psender: "0x00a329c0648769A73afAc7F9381E08FB43dBEA72"
coverage: true
format: text
`;
  }

  generateAll(parsedResults) {
    const harnesses = [];
    for (const file of parsedResults) {
      if (file.error) continue;
      for (const contract of file.contracts || []) {
        const echidna = this.generateEchidnaHarness(contract);
        const medusa = this.generateMedusaHarness(contract);
        harnesses.push({
          contract: contract.name,
          file: file.file,
          echidna,
          medusa,
          invariantCount: echidna.invariants.length,
        });
      }
    }
    return harnesses;
  }

  save(harnesses) {
    fs.mkdirSync(this.outputDir, { recursive: true });
    const manifest = [];
    for (const h of harnesses) {
      const echidnaDir = path.join(this.outputDir, 'echidna', h.contract);
      const medusaDir = path.join(this.outputDir, 'medusa', h.contract);
      fs.mkdirSync(echidnaDir, { recursive: true });
      fs.mkdirSync(medusaDir, { recursive: true });

      fs.writeFileSync(path.join(echidnaDir, `Echidna${h.contract}.sol`), h.echidna.harness);
      fs.writeFileSync(path.join(echidnaDir, 'echidna.yaml'), h.echidna.config);
      fs.writeFileSync(path.join(medusaDir, `Medusa${h.contract}.sol`), h.medusa.harness);
      fs.writeFileSync(path.join(medusaDir, 'medusa.json'), h.medusa.config);

      manifest.push({
        contract: h.contract,
        invariants: h.invariantCount,
        echidnaHarness: `echidna/${h.contract}/Echidna${h.contract}.sol`,
        echidnaConfig: `echidna/${h.contract}/echidna.yaml`,
        medusaHarness: `medusa/${h.contract}/Medusa${h.contract}.sol`,
      });
    }
    fs.writeFileSync(path.join(this.outputDir, 'manifest.json'), JSON.stringify(manifest, null, 2));
    return manifest;
  }

  parseEchidnaOutput(output) {
    const findings = [];
    const lines = output.split('\n');
    for (const line of lines) {
      const match = line.match(/echidna_(\w+):\s+([\s\S]+?)(?:\n|$)/);
      if (match && match[2].trim() !== 'passing') {
        findings.push({
          title: `Fuzz: Echidna broke invariant ${match[1]}`,
          severity: 'high',
          skill: 'fuzzing',
          evidence: match[2].trim(),
          impact: `Invariant ${match[1]} can be violated — indicates a logic bug or exploit path`,
          remediation: `Investigate the call sequence that breaks ${match[1]} and add proper validation`,
        });
      }
    }
    return findings;
  }
}

module.exports = FuzzingEngine;
